### PR TITLE
[WASH-934] Add revoke record method to iOS Plugin

### PR DESCRIPTION
**Pull request by Mrhea**
- Adds revoke method to iOS plugin
- Adds a revoke method to Dart frontend used in testing
  the plugins

Tested via the `onWriteThenShareButtonPress` method by adding a call to the new `revoke` method in `main.dart`.

### CODE REVIEW

**Review by efabens — APPROVED** [review]
With that manual testing it has also been verified that the shared with client can no longer read said record?

**Comment by Mrhea** [comment]
> With that manual testing it has also been verified that the shared with client can no longer read said record?

Hmm... I will confirm this. My manual testing had the visual of the dashboard showing the record for the client shared with, then afterwards no longer there after being revoked. I will test reading it after revoking 👍

**Review by pirtleshell — APPROVED** [review]
revoke method looks good.

with create, read, share, revoke implemented, it feels like a worthwhile investment to write an integration test for revoking a shared record and ensuring attempting to read it as the now-revoked user behaves as expected (raises an error w/ READ_RECORD code?).

**Comment by efabens** [comment]
> > With that manual testing it has also been verified that the shared with client can no longer read said record?
> 
> Hmm... I will confirm this. My manual testing had the visual of the dashboard showing the record for the client shared with, then afterwards no longer there after being revoked. I will test reading it after revoking 👍

The dashboard makes the read call, so if that has been confirmed then it shows it is working. I also agree that it will be nice to get some actual tests into this. Given the pace we are now moving I have hope for that soon

**Comment by Mrhea** [comment]
> > > With that manual testing it has also been verified that the shared with client can no longer read said record?
> > 
> > 
> > Hmm... I will confirm this. My manual testing had the visual of the dashboard showing the record for the client shared with, then afterwards no longer there after being revoked. I will test reading it after revoking 👍
> 
> The dashboard makes the read call, so if that has been confirmed then it shows it is working. I also agree that it will be nice to get some actual tests into this. Given the pace we are now moving I have hope for that soon

Agreed on all fronts! I think adding a new ticket for integration tests for Flutter would be a good idea. I just did the manual confirmation that a client reading a revoked record returns the expected 404. 

I have been imagining that there is a better way to error handle in the iOS plugin, too. Making that more robust is on my mind

**Review by galxy25 — APPROVED** [review]

**Pull request merged**
